spring:
  liquibase:
    change-log: classpath:/db/db-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:15432/database
    username: user
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  file-size: 10485760

server:
  address: localhost
  port: 8080

logging:
  level:
    "liquibase": info
